"""empty message

Revision ID: 4c1fce4569b1
Revises: ca4ae4b1c695
Create Date: 2023-09-02 11:12:32.180811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1fce4569b1'
down_revision = 'ca4ae4b1c695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('room', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['owner'], ['id'])
        batch_op.create_foreign_key(None, 'room', ['room'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
