"""empty message

Revision ID: 5674141fb1c2
Revises: 8fbe4553acb2
Create Date: 2023-09-01 22:35:55.748166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5674141fb1c2'
down_revision = '8fbe4553acb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.alter_column('owner',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('owner',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('active')

    # ### end Alembic commands ###
