"""empty message

Revision ID: ca4ae4b1c695
Revises: 902bd069c275
Create Date: 2023-09-02 11:11:49.516176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca4ae4b1c695'
down_revision = '902bd069c275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('message_ibfk_2', type_='foreignkey')
        batch_op.drop_column('room')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('room', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('message_ibfk_2', 'room', ['room'], ['id'])
        batch_op.create_foreign_key('message_ibfk_1', 'user', ['owner'], ['id'])

    # ### end Alembic commands ###
